title: Blog
description: Researcher / Data Scientist
author: Khoi-Nguyen Tran
github: https://github.com/kndtran
about: I am a researcher and data scientist. I specialise in text mining and  machine learning applications. Also, "Nguyen" is my first name! XD
username: kndtran
disqus_shortname: kndtran
google_analytics: UA-XXXXXXXX-Y

future: true
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/kndtran"
#    - icon: fa-twitter
#      link: "https://twitter.com/kndtran"
    - icon: fa-linkedin
      link: "https://au.linkedin.com/in/kndtran"
    - icon: fa-github
      link: "https://github.com/kndtran"

# http://fontawesome.io/icons/

share:
  twitter_username: kndtran
  fb_appid: 0

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Google Scholar
      url: https://scholar.google.com.au/citations?user=ihFcT5QAAAAJ&hl=en

url: "https://kndtran.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
