# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nguyen
tagline:          'Researcher / Data Scientist'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://kndtran.github.io
baseurl:          /

author:
  name:           'Khoi-Nguyen Tran'
  url:            https://twitter.com/kndtran

gems:							[jekyll-paginate]
paginate:         5
paginate_path:		"page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kndtran
