# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://kndtran.github.io/
baseurl: 
title: Khoi-Nguyen Tran
author: Khoi-Nguyen Tran
description: Resume and personal site
avatar: profile2.jpeg
#email: kndtran@gmail.com
facebook: kndtran
github: kndtran
#twitter: kndtran
linkedin: kndtran
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1
gscholar: ihFcT5QAAAAJ
researchgate: Khoi_Nguyen_Tran

# needed for travis-ci build
exclude: [vendor]
